Repository arduino-libraries/Arduino_UnifiedStorage, pull requests merged in 2023-09, with the labels that each got.

#8 [AE-158] Use POSIXStorage from lib manager
  .github/workflows/compile-examples.yml
Labels: topic: infrastructure, status: in progress, criticality: medium

#12 Refactor variable names and remove unused code
  examples/BackupInternalPartitions/BackupInternalPartitions.ino
  extras/tests/TestExisting/TestExisting.ino
  extras/tests/TestFileOperations/TestFileOperations.ino
  extras/tests/TestFolderOperations/TestFolderOperations.ino
  keywords.txt
  src/Folder.cpp
  src/Folder.h
  src/InternalStorage.cpp
  src/InternalStorage.h
  src/Types.h
  src/UFile.cpp
  src/UFile.h
  src/USBStorage.cpp
  src/USBStorage.h
Labels: topic: documentation, type: enhancement, topic: code

#13 [AE-158] Specify compatible sketches for each `fqbn:`
  .github/workflows/compile-examples.yml
Labels: type: imperfection, topic: infrastructure

#17 Clean up Code
  src/Arduino_UnifiedStorage.h
  src/InternalStorage.cpp
  src/InternalStorage.h
  src/SDStorage.cpp
  src/SDStorage.h
  src/USBStorage.cpp
  src/USBStorage.h
Labels: topic: code

#16 Apply suggestions from Per's review
  .github/workflows/compile-examples.yml
Labels: type: imperfection, topic: infrastructure

#18 [AE-158] Make readme more user-friendly
  README.md
Labels: topic: documentation, type: enhancement
